version: 2.1

executors:
  core_sdk:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1

jobs:
  build:
    executor: core_sdk
    steps:
        - checkout
        - run: |
            dotnet restore
            dotnet build -c Release -p:PackageVersion=1.0.0
            dotnet pack -c Release -p:PackageVersion=1.0.0
  build-n-push:
    executor: core_sdk
    steps:
        - checkout
        - run: |
            dotnet restore
            dotnet build -c Release -p:PackageVersion=$CIRCLE_TAG
            dotnet pack -c Release -p:PackageVersion=$CIRCLE_TAG
            cd ./bin/Release/
            dotnet nuget push Gaardsholt.ApiKeyAuthMiddleware.$CIRCLE_TAG.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: gaardsholt
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
  build-n-push:
    jobs:
      - build-n-push:
          context: gaardsholt
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/